### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by ErikPlachta** [ErikPlachta/Purrfect-Friend#23]
## Project Requirements 

- [x] 1. Must use at least two server-side APIs #4 
- [x] 2. Must use a CSS framework other than bootstrap #1 
- [x] 3. Must use client-side storage for persistent data #6 
- [x] 4. Must have a polished, mobile-first UI #8 
- [x] 5. Must meet good quality coding standards ( indentation, scoping,  naming, etc. ) #9 
- [x] 6. Does NOT use alerts, confirms, or prompts ( *use modals* ) #5 
- [x] 7. Must be deployed to GitHub Pages #2 
- [x] 8. Must be interactive (i.e., accept and respond to user input) #3 

![image](https://user-images.githubusercontent.com/17508965/145127549-71cc39c8-d3f4-48de-8385-f69b9c54f0ec.png)

**Comment by ErikPlachta** [comment]
Reopened. Shouldn't be closed.

**Comment by barrantesc** [comment]
Verified and completed project requirements. Requested quality review by @ErikPlachta @etdorikin

**Comment by ErikPlachta** [comment]
Looks great.

Go ahead and close @etdorikin once you're good.

**Comment by etdorikin** [comment]
Everythings good
